name: Build and Upload Resume

on:
  push:
    branches:
      - main
    paths:
      - "resume.tex"
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    container:
      image: blang/latex:ctanfull  # Preinstalled full TeX Live

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Compile the resume.tex to PDF
      - name: Compile resume.tex
        run: |
          pdflatex resume.tex

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 4. Upload to S3 (make public)
      - name: Upload resume.pdf to S3
        run: |
          aws s3 cp resume.pdf s3://prashant-dhirendra-resume-bucket/resume.pdf
